# Site settings
title: Meet @fannheyward
author: "Heyward Fann"
email: fannheyward@gmail.com
description: "Heyward Fann, aka fannheyward, a developer based in Beijing, China."
baseurl: ""
url: "https://fann.im"

github_username:  fannheyward

twitter:
  username: "fannheyward"

facebook:
  admins: fannheyward

social:
  links:
    - https://twitter.com/fannheyward
    - https://github.com/fannheyward
    - https://www.facebook.com/fannheyward

# Build settings
permalink: /blog/:year/:month/:day/:title/

paginate: 10
paginate_path: "blog/page/:num/"

kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-gist

