# Site settings
title: Meet @fannheyward
email: fannheyward@gmail.com
description: "Heyward Fann, aka fannheyward, a developer based in Beijing, China."
baseurl: ""
url: "http://fann.im"

github_username:  fannheyward
google_plus: 117945530073148473022
google_analytics_tracking_id: UA-5304377-4

author:
  username: "Heyward Fann"
  twitter: fannheyward

twitter:
  username: fannheyward

facebook:
  admins: fannheyward

social:
  links:
    - https://github.com/fannheyward
    - https://www.facebook.com/fannheyward
    - https://plus.google.com/+HeywardFann

# Build settings
permalink: /blog/:year/:month/:day/:title/

paginate: 10
paginate_path: "blog/page/:num"

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-gist

