# Site settings
title: Meet @fannheyward
author: "Heyward Fann"
email: fannheyward@gmail.com
description: "Heyward Fann, aka fannheyward, aim to be a Full Stack Developer, blog about development and my life."
baseurl: ""
url: "http://fann.im"
twitter_username: fannheyward
github_username:  fannheyward
google_plus: 117945530073148473022
google_analytics_tracking_id: UA-5304377-4

# Build settings
permalink: /blog/:year/:month/:day/:title/

paginate: 10
paginate_path: "blog/page/:num"

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

